import { Sidebar } from '@/components/sidebar/'
import Head from 'next/head'
import { Inter } from '@next/font/google'
import type { TNavSection } from '@/components/sidebar/nav-list'
import { Drawer } from '@/components/drawer'
import { MaterialIcon } from '@/components/ui/MaterialIcon'
import { useState } from 'react'
import { basic, exampleWithLabel } from '@/data/menus'
import { profiles } from '@/data/profiles'

const inter = Inter({ subsets: ['latin'] })

const navs: TNavSection[] = [basic, exampleWithLabel]
const profile = profiles[0]

export default function Home() {
  const [showSidebar, showSidebarSet] = useState(true)

  return (
    <div className="flex flex-col sm:flex-row">
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Drawer show={showSidebar} static>
        <Sidebar
          header={
            profile && {
              title: profile.name,
              subtitle: profile.email,
              image: profile.image,
            }
          }
          navs={navs}
        />
      </Drawer>
      <main className={inter.className}>hello world</main>
      <button
        className="fixed bottom-4 right-4 flex aspect-square h-10 w-10 items-center justify-center rounded-full border bg-indigo-600 text-indigo-100"
        onClick={() => showSidebarSet((prev) => !prev)}
      >
        <MaterialIcon name="menu" />
      </button>
    </div>
  )
}
